import assert from 'node:assert/strict'
import { registerHooks } from 'node:module'
registerHooks({resolve(s,c,next){return next(s==='../types'?'../types.ts':s,c)}})
const { DemoRepository } = await import('../src/data/demoRepository.ts')
const repo = new DemoRepository()
await repo.signInDemo('leader')
const before = await repo.getDashboard()
const uploaded = await repo.uploadDocument('ana-torres','IMAGE_AUTHORIZATION',new File(['test'],'test.png',{type:'image/png'}))
let doc = uploaded.documents.find(d=>d.type==='IMAGE_AUTHORIZATION')
assert.equal(doc.versionNumber,2)
assert.equal(doc.history[0].status,'OBSERVED')
assert.equal(doc.analysis.status,'PENDING')
assert.equal((await repo.getDashboard()).attention,before.attention-1)
await assert.rejects(repo.reviewDocument(doc.versionId,'APPROVED',''),/equipo FSY/)
await repo.signInDemo('admin')
await assert.rejects(repo.confirmParticipant('ana-torres'),/cada documento/)
await assert.rejects(repo.reviewDocument(doc.versionId,'OBSERVED',''),/Explica/)
await repo.reviewDocument(doc.versionId,'OBSERVED','Muestra las esquinas')
const replacement=await repo.uploadDocument('ana-torres','IMAGE_AUTHORIZATION',new File(['test2'],'test2.png',{type:'image/png'}))
doc = replacement.documents.find(d=>d.type==='IMAGE_AUTHORIZATION')
assert.equal(doc.versionNumber,3)
assert.equal(doc.history.length,2)
await new Promise(resolve=>setTimeout(resolve,1900))
assert.equal((await repo.getParticipant('ana-torres')).documents.find(d=>d.type==='IMAGE_AUTHORIZATION').analysis.status,'COMPLETE')
await repo.reviewDocument(doc.versionId,'APPROVED','')
await repo.confirmParticipant('ana-torres')
assert.equal((await repo.getParticipant('ana-torres')).status,'CONFIRMED')
await assert.rejects(repo.uploadDocument('ana-torres','IMAGE_AUTHORIZATION',new File(['x'],'x.png',{type:'image/png'})),/cambios/)
console.log('OK demo: carga, análisis asíncrono, conteos, roles, observación, historial, aprobación y confirmación.')
const input={unitId:'unit-ventanilla',firstName:'Lucia',lastName:'Prueba',birthDate:'2010-04-10',sex:'Mujer',guardianFirstName:'Tutor',guardianLastName:'Prueba'}
await repo.signInDemo('leader')
await assert.rejects(repo.startReplacement('ana-torres',{...input,sex:'Hombre'},'Cambio'),/mismo sexo/)
const baseline=(await repo.getDashboard()).total
const incoming=await repo.startReplacement('ana-torres',input,'No podrá asistir')
const request=(await repo.getReplacements(incoming))[0]
assert.equal((await repo.getDashboard()).total,baseline)
await assert.rejects(repo.startReplacement('ana-torres',input,'Duplicado'),/en proceso/)
await assert.rejects(repo.transitionReplacement(request.id,'SUBMITTED'),/documentos/)
for(const d of (await repo.getParticipant(incoming)).documents)await repo.uploadDocument(incoming,d.type,new File(['test'],'test.png',{type:'image/png'}))
await repo.transitionReplacement(request.id,'SUBMITTED')
await assert.rejects(repo.transitionReplacement(request.id,'APPROVED'),/equipo FSY/)
await repo.signInDemo('admin')
await assert.rejects(repo.confirmParticipant(incoming),/solicitud/)
await assert.rejects(repo.transitionReplacement(request.id,'APPROVED'),/documentos/)
for(const d of (await repo.getParticipant(incoming)).documents)await repo.reviewDocument(d.versionId,'APPROVED','')
await repo.transitionReplacement(request.id,'APPROVED')
assert.equal((await repo.getParticipant(incoming)).status,'CONFIRMED')
assert.equal((await repo.getParticipant('ana-torres')).status,'REPLACED')
assert.equal((await repo.getDashboard()).total,baseline)
await assert.rejects(repo.transitionReplacement(request.id,'APPROVED'),/estado/)
const cancelId=await repo.startReplacement(incoming,{...input,firstName:'Otro'},'Segundo cambio')
const cancel=(await repo.getReplacements(cancelId))[0]
await repo.transitionReplacement(cancel.id,'CANCELLED')
assert.equal((await repo.getParticipant(incoming)).status,'CONFIRMED')
assert.equal((await repo.getParticipant(cancelId)).status,'CANCELLED')
assert.equal((await repo.getDashboard()).total,baseline)
console.log('OK MVP3 demo: sexo, cupo único, documentos, roles, aprobación, historial y cancelación.')
